from . import calendar_event
from . import clinic_history
from . import customer_contract
from . import hr_specialty
from . import project_project
from . import project_task
from . import res_locality
from . import res_neighborhood
from . import res_partner
from . import res_users
from . import project_task_product
from . import project_task_product_extra
